# Generated by Django 4.1 on 2023-03-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.EmailField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
