# Generated by Django 4.1 on 2023-03-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='customer',
        ),
    ]
