# Generated by Django 4.1 on 2023-03-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping_App', '0003_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='PhoneNumber',
            field=models.IntegerField(default='foobar'),
        ),
    ]
