# Generated by Django 4.1 on 2023-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoping_App', '0005_alter_customer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(max_length=100),
        ),
    ]
