from django.urls import path

from Shoping_App import views

urlpatterns = [
    path('', views.Shoping_App, name = "index"),
    path("about/", views.about, name = "about" ),
    path("blog/", views.blog, name ="blog"),
    path("blogimg/", views.blogimg, name = "blogimg"),
    path("blogvid/", views.blogvid, name = "blogvid"),
    path("blogaud/", views.blogaud, name = "blogaud"),
    path("blogfull1/", views.blogfull1, name = "blogfull1"),
    path("blogfull2/", views.blogfull2, name = "blogfull2"),
    path("blogleft/", views.blogleft, name = "blogleft"),
    path("blogleft2/", views.blogleft2, name = "blogleft2"),
    path("blogright/", views.blogright, name = "blogright"),
    path("compare/", views.compare, name = "compare"),
    path("checkout/", views.checkout, name = "checkout"),
    path("contactus/", views.contactus, name = "contactus"),
    path("cart/", views.cart, name = "cart"),
    path("index2/", views.index2, name = "index2"),
    path("index3/", views.index3, name = "index3"),
    path("index4/", views.index4, name = "index4"),
    path("loginreg/", views.loginreg, name = "reg"),
    path("myaccount/", views.myaccount, name = "myaccount"),
    path("paffilate/", views.paffilate, name = "paffilate"),
    path("pbox/", views.pbox, name = "pbox"),
    path("pdetailsgroup/", views.pdetailsgroup, name = "pdetailsgroup"),
    path("pdetailsvar/", views.pdetailsvar, name = "pdetailsvar"),
    path("productdetails/", views.productdetails, name = "productdetails"),
    path("shopgrid3/", views.shopgrid3, name = "shopgrid3"),
    path("shopgrid4/", views.shopgrid4, name = "shopgrid4"),
    path("shopgridleft/", views.shopgridleft, name = "shopgridleft"),
    path("shopgridleft3/", views.shopgridleft3, name = "shopgridleft3"),
    path("shopgridright/", views.shopgridright, name = "shopgridright"),
    path("shopgridright3/", views.shopgridright3, name = "shopgridright3"),
    path("shoplistfull/", views.shoplistfull, name = "shoplistfull"),
    path("shoplistleft/", views.shoplistleft, name = "shoplistleft"),
    path("shoplistright/", views.shoplistright, name = "shoplistright"),
    path("singleprodgroup/", views.singleprodgroup, name = "singleprodgroup"),
    path("singleproduct/", views.singleproduct, name = "singleproduct"),
    path("singleprosale/", views.singleprosale, name = "singleprosale"),
    path("wishlist/", views.wishlist, name = "wishlist"),
    path("signin/", views.signin, name = "signin"),
    
]